language:
    - php

php:
    - "5.5"
    - "5.4"
    - "5.3"

before_script:
    - composer install --dev --no-interaction
    - mkdir -p build/logs
    - mv tests/phpunit.xml.ci tests/phpunit.xml

script:
    - phpunit --configuration tests/phpunit.xml

after_script:
    - php vendor/bin/coveralls
