language:
    - php

php:
    - "5.5"
    - "5.4"
    - "5.3"
    - "5.2.4"

before_script:
    - composer install --dev --no-interaction
    - mkdir -p build/logs

script:
    - phpunit --configuration tests/phpunit.xml.ci

after_script:
    - php vendor/bin/coveralls
